# Generated by Django 6.0.6 on 2026-06-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('image', models.ImageField(upload_to='posters/', verbose_name='صورة البوستر')),
                ('description', models.TextField(verbose_name='الوصف الطبي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
