# Generated by Django 4.2.30 on 2026-06-19 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0003_staticpage_alter_poster_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaharChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='القسم')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ المراجعة')),
                ('patient_id_verified', models.BooleanField(default=False, verbose_name='التأكد من هوية المريض')),
                ('policies_updated', models.BooleanField(default=False, verbose_name='السياسات محدثة')),
                ('hand_hygiene_followed', models.BooleanField(default=False, verbose_name='الالتزام بغسل الأيدي')),
                ('waste_segregation_correct', models.BooleanField(default=False, verbose_name='فصل النفايات صحيح')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
            ],
        ),
    ]
