# Generated by Django 4.2.30 on 2026-06-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_gaharchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='x',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='x',
            name='title',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
