# Generated by Django 4.2.30 on 2026-06-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_x_content_x_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='x',
        ),
    ]
